#
# Pod manifest to test node drain
# Faulty finalizer is added to prevent deletion of the pod which subsequently prevents node drain
# The command to manually solve this issue is to remove the faulty finalizer:
# COMMAND: `oc patch pod node-drain-test -p '{"metadata":{"finalizers":[]}}' --type=merge`
#
apiVersion: v1
kind: Pod
metadata:
  name: node-drain-test
  finalizers:
  - ingress.openshift.io/canttouchthis
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"

